### ISSUE TITLE
DOB entry

### ISSUE THREAD

**Issue by BenService** [Artanemus/SCM_SwimClubMeet-R#3]
In the latest version of SwimClubMeet when I go to enter a new member I can't just type their DOB in I have to use all the clicky button things to select it, it all looks funky but it is a bit slow vs just typing it in.  Is there something I am missing or an easy fix for this?  I am mainly worried on sign up night trying to get a lot of new swimmers entered quickly.

**Comment by Artanemus** [comment]
Currently I'm coding in the 1.5.5.3 fork. I could make changes to 1.5.5.2 (resolving the DOB issue) and then build a 1.5.5.21 version. BUT I'm a little fearful that that merging 1.5.5.3 back into the main branch may be a complicated by all the various changes that I've made. 
So to go forward I will offer a alternative DOB UI in version 1.5.5.3. ETA on 1.5.5.3 - good question! I'll do my best.

**Comment by BenService** [comment]
No rush, swim season doesn’t start until late September and what we have works so it’s not the end of the world.

Sent from my iPhone

On 4 Aug 2023, at 4:57 pm, Ben Ambrose ***@***.***> wrote:

﻿

Currently I'm coding in the 1.5.5.3 fork. I could make changes to 1.5.5.2 (resolving the DOB issue) and then build a 1.5.5.21 version. BUT I'm a little fearful that that merging 1.5.5.3 back into the main branch may be a complicated by all the various changes that I've made.
So to go forward I will offer a alternative DOB UI in version 1.5.5.3. ETA on 1.5.5.3 - good question! I'll do my best.

**Comment by Artanemus** [comment]
In version 1.5.5.3 (to be released soon) you now have the option to use either a DOB picker or just type the DOB

![image](https://github.com/Artanemus/SCM_SwimClubMeet-R/assets/69775305/bfda655a-2897-4f2b-89d8-ca5b9dc4c93f)

So Americans and the rest of the world have the correct date display and data entry syntax the edit cell for DOB uses the Region Settings used by MS Windows

![image](https://github.com/Artanemus/SCM_SwimClubMeet-R/assets/69775305/00bb68f9-15a1-4852-aa76-35cf1e0de15c)

You can press the info icon 'bug' for some helpful insight - should you have trouble entering dates.
Another worthy note: If you need to see 4 digits for the YEAR, then go to the Windows region settings and change the 'Short Date' format to  - dd/mm/yyyy
